using System.Globalization;
namespace AntonsBackupManager.App;

internal static class UiText
{
    private static string language = "de";
    public static event EventHandler? LanguageChanged;
    public static string Language
    {
        get => language;
        set
        {
            if (language == value) return;
            language = value;
            LanguageChanged?.Invoke(null, EventArgs.Empty);
        }
    }
    public static readonly Dictionary<string, string[]> Entries = new()
    {
        ["AppStartFailed"] = ["Die Anwendung konnte nicht gestartet werden.", "The application could not start.", "Не удалось запустить приложение."],
        ["VolumeMissing"] = ["Der zugeordnete Datenträger ist nicht verfügbar. Nach dem Anschließen erneut prüfen.", "The bound drive is unavailable. Reconnect it and preview again.", "Привязанный накопитель недоступен. После подключения проверьте задачу заново."],
        ["VolumeAmbiguous"] = ["Mehrere Datenträger haben dieselbe Kennung. Die Zuordnung ist nicht eindeutig; es wird nichts gestartet.", "Multiple drives have the same identity. The binding is ambiguous; synchronization will not start.", "У нескольких накопителей одинаковый номер. Привязка неоднозначна, синхронизация не запускается."],
        ["VolumeRebind"] = ["Die alte Zuordnung enthält keine Ordnerrolle. Aktuelle Ordner wählen und den Datenträger erneut zuordnen.", "The old binding does not identify the folder role. Select the current folders and bind the drive again.", "В старой привязке не указано, какая папка относится к флешке. Выберите актуальные папки и привяжите накопитель заново."],
        ["WelcomeTitle"] = ["Wähle zwei Ordner.", "Start with two folders.", "Начните с двух папок."],
        ["WelcomeBody"] = ["Quelle und Ziel auswählen, dann den Plan prüfen. Du entscheidest, wann synchronisiert wird.", "Choose a source and destination, then preview the plan. You decide when to synchronize.", "Выберите источник и назначение, затем проверьте список. Синхронизация начинается по вашему решению."],
        ["RenameDestinationFile"] = ["Umbenennen", "Rename", "Переименовать"],
        ["RetryLockedFile"] = ["Belegt · später", "Busy · retry later", "Занят · повтор позже"],
        ["RetryPending"] = ["Wiederholung ausstehend", "Retry pending", "Ожидает повтора"],
        ["SyncExtra"] = ["Umbenennen: {0} · Belegt: {1}", "Rename: {0} · Busy: {1}", "Переименовать: {0} · Занято: {1}"],
        ["SyncDone"] = ["Kopiert: {0} · Umbenannt: {1} · Konflikte: {2} · Später erneut: {3}", "Copied: {0} · Renamed: {1} · Conflicts: {2} · Retry later: {3}", "Скопировано: {0} · Переименовано: {1} · Конфликты: {2} · Повтор позже: {3}"],
        ["TrayDeferred"] = ["{0} Dateien sind belegt. Wiederholung beim nächsten Lauf.", "{0} files are busy. Retrying on the next run.", "Занято файлов: {0}. Повторим при следующем запуске."],
        ["OpenShort"] = ["Öffnen", "Open folder", "Открыть"],
        ["Compare"] = ["Vergleichen", "Compare", "Сравнить"],
        ["KeepDestination"] = ["Ziel behalten", "Keep destination", "Оставить назначение"],
        ["Absent"] = ["Datei fehlt", "File absent", "Файл отсутствует"],
        ["FileDetails"] = ["Größe: {0:N0} Bytes\nGeändert: {1}\n\nSHA-256:\n{2}", "Size: {0:N0} bytes\nModified: {1}\n\nSHA-256:\n{2}", "Размер: {0:N0} байт\nИзменён: {1}\n\nSHA-256:\n{2}"],
        ["DecisionHint"] = ["Entscheidung mit «Synchronisieren» übernehmen. Quelle überschreibt das Ziel mit vorheriger Version. «Ziel behalten» bleibt bis zur nächsten Änderung bestehen.", "Apply the decision with Synchronize. Use source keeps a previous destination version. Keep destination lasts until either side changes.", "Примените решение кнопкой «Синхронизировать». Замена из источника сохраняет прежнюю версию. Решение «Оставить назначение» действует до изменения одной из сторон."],
        ["ApprovalShort"] = ["Bestätigung erforderlich", "Approval required", "Нужно подтверждение"],
        ["NeverRun"] = ["Noch nie", "Not yet", "Ещё не было"],
        ["Soon"] = ["Sobald bereit", "When ready", "Когда задача готова"],
        ["TaskTiming"] = ["Zuletzt: {0}\nAlle {1} Min. · Nächste: {2}", "Last run: {0}\nEvery {1} min · Next: {2}", "Запуск: {0}\nКаждые {1} мин · Следующий: {2}"],
        ["ResetSafety"] = ["Wieder fünfmal bestätigen", "Require five confirmations again", "Снова пять подтверждений"],
        ["UsbBind"] = ["Laufwerk zuordnen", "Bind drive", "Привязать накопитель"],
        ["UsbUnbind"] = ["Lösen", "Unbind", "Отвязать"],
        ["UsbNotBound"] = ["Kein Wechseldatenträger zugeordnet.", "No removable drive bound.", "Накопитель не привязан."],
        ["UsbBound"] = ["Wechseldatenträger zugeordnet. Mit «Prüfen» speichern.", "Removable drive bound. Save with Preview.", "Накопитель привязан. Сохраните кнопкой «Проверить»."],
        ["UsbUnavailable"] = ["Kein erreichbarer Wechseldatenträger in Quelle oder Ziel.", "No available removable drive in source or destination.", "В источнике или назначении нет доступного съёмного накопителя."],
        ["PauseAll"] = ["Alle pausieren", "Pause all tasks", "Пауза всех задач"],
        ["ResumeAll"] = ["Alle fortsetzen", "Resume all tasks", "Возобновить все"],
        ["AllPaused"] = ["Alle Synchronisierungen pausiert. Die aktuelle Datei wird abgeschlossen.", "All synchronization paused. The current file will finish.", "Вся синхронизация на паузе. Текущий файл будет завершён."],
        ["AllResumed"] = ["Globale Pause aufgehoben. Aktivierte Aufgaben laufen wieder.", "Global pause lifted. Enabled tasks will run again.", "Общая пауза снята. Включённые задачи снова будут запускаться."],
        ["Advanced"] = ["Sicherheit und Versionen", "Safety and versions", "Защита и версии"],
        ["SafetyMode"] = ["Die ersten fünf Läufe bestätigen", "Confirm the first five runs", "Подтверждать первые пять запусков"],
        ["SafetyInitial"] = ["5 Bestätigungen. Danach automatisch, wenn aktiviert.", "5 confirmations. Then automatic, if enabled.", "5 подтверждений. Затем автоматически, если задача включена."],
        ["SafetyCount"] = ["Verbleibende Bestätigungen: {0}. Änderungen mit «Prüfen» übernehmen.", "Confirmations remaining: {0}. Apply changes with Preview.", "Осталось подтверждений: {0}. Изменения применяются кнопкой «Проверить»."],
        ["VersionLimit"] = ["Versionen je Datei (1–100):", "Versions per file (1–100):", "Версий каждого файла (1–100):"],
        ["NeedsApproval"] = ["Sicherheitsmodus: noch {0} Bestätigungen. Aufgabe prüfen und manuell synchronisieren.", "Safety mode: {0} confirmations remain. Preview the task and synchronize manually.", "Защита: осталось подтверждений — {0}. Проверьте задачу и запустите синхронизацию вручную."],
        ["AutomaticRun"] = ["Automatisch", "Automatic", "Автоматически"],
        ["ManualRun"] = ["Manuell", "Manual", "Вручную"],
        ["Completed"] = ["Abgeschlossen", "Completed", "Завершено"],
        ["Interrupted"] = ["Unterbrochen", "Interrupted", "Прервано"],
        ["Failed"] = ["Fehlgeschlagen", "Failed", "Ошибка"],
        ["Details"] = ["Fehlerdetails", "Error details", "Подробнее об ошибке"],
        ["StateOverlap"] = ["Der gewählte Ordner überschneidet sich mit den Arbeitsdaten der Anwendung.", "The selected folder overlaps the application's working data.", "Выбранная папка пересекается с рабочими данными программы."],
        ["StateOverlapDetails"] = ["Die Anwendung verändert diese Daten während ihrer Arbeit. Wähle andere Ordner oder bewahre die Anwendung außerhalb der gewählten Ordner auf.\nFür eine Kopie der Anwendung selbst: im Infobereich beenden und den gesamten Programmordner im Explorer kopieren.\n\n{0}: {1}\nArbeitsdaten: {2}", "The app changes this data while running. Choose other folders or keep the app outside the selected folders.\nTo copy the app itself: exit through the tray and copy its entire folder in File Explorer.\n\n{0}: {1}\nWorking data: {2}", "Программа изменяет эти данные во время работы. Выберите другие папки или храните программу за пределами выбранных папок.\nЧтобы скопировать саму программу: выйдите через трей и скопируйте всю её папку в Проводнике.\n\n{0}: {1}\nРабочие данные: {2}"],
        ["ErrorCode"] = ["Diagnosecode: {0} / 0x{1}", "Diagnostic code: {0} / 0x{1}", "Код диагностики: {0} / 0x{1}"],
        ["WaitingForFile"] = ["Die aktuelle Hintergrunddatei wird abgeschlossen …", "Finishing the current background file …", "Завершаем текущий файл фоновой задачи…"],
        ["ScanningFile"] = ["Inhalt wird geprüft: {0}", "Checking content: {0}", "Проверяем содержимое: {0}"],
        ["EmptySaved"] = ["Aufgabe gespeichert. Der Quellordner ist leer; füge Dateien hinzu und prüfe erneut.", "Task created. The source is empty; add files and preview again.", "Задача создана. Источник пуст — добавьте файлы и проверьте ещё раз."],
        ["LinkBlocked"] = ["Dieser Ordner enthält einen nicht unterstützten Link. Siehe Details.", "This folder contains an unsupported link. See details.", "В папке обнаружена неподдерживаемая ссылка. Подробности ниже."],
        ["UnsupportedLink"] = ["Link oder Einbindung wird nicht verfolgt: {0}", "Link or junction will not be followed: {0}", "Символическая ссылка или подключённая папка не обрабатывается: {0}"],
        ["PauseTask"] = ["Pause", "Pause task", "Пауза"],
        ["ResumeTask"] = ["Fortsetzen", "Resume task", "Возобновить"],
        ["TaskPaused"] = ["Aufgabe pausiert. Die aktuelle Datei wird noch abgeschlossen.", "Task paused. The current file will finish first.", "Задача на паузе. Если файл уже копируется, он будет завершён."],
        ["TaskResumed"] = ["Automatische Synchronisierung aktiviert.", "Automatic synchronization enabled.", "Автоматическая синхронизация включена."],
        ["TrayIdle"] = ["Wartet", "Waiting", "Ожидание"],
        ["TrayReadyState"] = ["Synchronisiert", "Synchronized", "Синхронизировано"],
        ["TrayAttention"] = ["Bitte prüfen", "Needs attention", "Требуется проверка"],
        ["BackgroundCheck"] = ["Hintergrund", "Background", "Фоновый режим"],
        ["CheckInTray"] = ["Im Tray prüfen", "Check in tray", "Проверять в трее"],
        ["AutoSyncEvery"] = ["Automatisch synchronisieren alle:", "Automatically synchronize every:", "Проверять автоматически каждые:"],
        ["Automatic"] = ["● Automatisch", "● Automatic", "● Автоматически"],
        ["Paused"] = ["○ Pausiert", "○ Paused", "○ На паузе"],
        ["Interval"] = ["Prüfintervall", "Check interval", "Интервал проверки"],
        ["TrayChanges"] = ["Neu: {0} · Aktualisieren: {1} · Konflikte: {2}", "New: {0} · Updates: {1} · Conflicts: {2}", "Новых: {0} · Обновить: {1} · Конфликтов: {2}"],
        ["TrayConflicts"] = ["{0} Konflikte. Bitte Aufgabe öffnen.", "{0} conflicts. Please open the task.", "Конфликтов: {0}. Откройте задачу."],
        ["TrayUnavailable"] = ["Ordner ist nicht verfügbar. Prüfung wird später wiederholt.", "A folder is unavailable. Checking will be retried later.", "Папка недоступна. Проверка будет повторена позже."],
        ["TrayOpen"] = ["Kaktus öffnen", "Open Kaktus", "Открыть Kaktus"],
        ["TrayExit"] = ["Beenden", "Exit", "Закрыть программу"],
        ["StartWithWindows"] = ["Mit Windows starten", "Start with Windows", "Запускать вместе с Windows"],
        ["StartupFailed"] = ["Autostart konnte nicht geändert werden.", "Could not change Windows startup.", "Не удалось изменить запуск с Windows."],
        ["OpenFolder"] = ["Ordner öffnen", "Open folder", "Открыть папку"],
        ["ResolveConflicts"] = ["Quelle übernehmen", "Use source", "Взять из источника"],
        ["ConflictHelp"] = ["Konflikte: {0}. Zeilen auswählen und «Quelle übernehmen», um sie zu ersetzen. Ohne Auswahl bleibt das Ziel unverändert.", "Conflicts: {0}. Select rows and choose “Use source” to replace them. Unselected conflicts keep the destination unchanged.", "Конфликтов: {0}. Выделите строки и нажмите «Взять из источника» для замены. Невыбранные конфликты останутся без изменений."],
        ["ResolveConfirm"] = ["Diese Zieldateien durch die Quelle ersetzen? Ihre bisherigen Versionen werden gespeichert. Zunächst wird nur der Plan geändert; Ausführung mit «Synchronisieren».\n\n{0}", "Replace these destination files with the source? Previous versions will be saved. This changes only the plan; run it with “Synchronize”.\n\n{0}", "Заменить эти файлы назначения файлами из источника? Прежние версии сохранятся. Сейчас изменится только план; запуск — кнопкой «Синхронизировать».\n\n{0}"],
        ["SyncSummary"] = ["Neu: {0} · Aktualisieren: {1} · Identisch: {2} · Konflikte: {3}", "New: {0} · Update: {1} · Identical: {2} · Conflicts: {3}", "Новых: {0} · Обновить: {1} · Совпадает: {2} · Конфликты: {3}"],
        ["NextSync"] = ["Aufgabe gespeichert. Vorschau prüfen und «Synchronisieren» wählen.", "Task saved. Review the preview, then choose “Synchronize”.", "Задача сохранена. Проверьте список и нажмите «Синхронизировать»."],
        ["SyncConfirm"] = ["Quelle → Ziel: {0} neue Dateien, {1} Aktualisierungen nach «{2}». Vorherige Versionen werden gespeichert. Konflikte werden übersprungen; nichts wird gelöscht.", "Source → destination: {0} new files, {1} updates to “{2}”. Previous versions are saved. Conflicts are skipped; nothing is deleted.", "Источник → назначение: новых файлов — {0}, обновлений — {1}, папка «{2}». Прежние версии сохраняются. Конфликты пропускаются, файлы не удаляются."],
        ["Versions"] = ["Versionen", "Versions", "Предыдущие версии"],
        ["History"] = ["Verlauf", "History", "История"],
        ["HistoryFor"] = ["Verlauf: {0}", "History: {0}", "История: {0}"],
        ["NoHistory"] = ["Noch keine Durchläufe für diese Aufgabe.", "No runs for this task yet.", "Для этой задачи запусков пока нет."],
        ["HistoryEntry"] = ["{0} · {1} Dateien · {2} Konflikte", "{0} · {1} files · {2} conflicts", "{0} · файлов: {1} · конфликтов: {2}"],
        ["Export"] = ["Als neue Datei wiederherstellen", "Restore as a new file", "Восстановить отдельным файлом"],
        ["Exported"] = ["Version als neue Datei wiederhergestellt.", "Version restored as a new file.", "Версия восстановлена отдельным файлом."],
        ["NoVersions"] = ["Noch keine vorherigen Versionen.", "No previous versions yet.", "Предыдущих версий пока нет."],
        ["NextCopy"] = ["Vorschau fertig. Klicke auf «Kopieren», um {0} neue Dateien zu kopieren. Danach bestätigst du den Vorgang.", "Preview ready. Click “Copy files” to copy {0} new files, then confirm.", "План готов. Нажмите «Копировать», чтобы скопировать новые файлы ({0}), затем подтвердите действие."],
        ["NextSave"] = ["Speichere diese Aufgabe und prüfe sie erneut, um das Kopieren freizugeben.", "Save this task and preview again to enable copying.", "Сохраните задачу и проверьте её повторно — после этого станет доступно копирование."],
        ["NoNew"] = ["Keine neuen Dateien. Unterschiedliche bestehende Dateien werden als Konflikte übersprungen.", "No new files. Existing files with different content are skipped as conflicts.", "Новых файлов нет. Существующие файлы с другим содержимым пропускаются как конфликты."],
        ["NextInspect"] = ["Aufgabe gespeichert. Klicke auf «Prüfen», um den Kopierplan zu sehen.", "Task saved. Click “Preview” to see the copy plan.", "Задача сохранена. Нажмите «Проверить», чтобы увидеть план копирования."],
        ["Continue"] = ["Bestätigen", "Confirm", "Подтвердить"],
        ["Tasks"] = ["AUFGABEN", "TASKS", "ЗАДАЧИ"],
        ["New"] = ["+ Neue Aufgabe", "+ New task", "+ Новая задача"],
        ["Local"] = ["●  Lokal & privat", "●  Local & private", "●  Локально и приватно"],
        ["Scope"] = ["Quelle → Ziel. Änderungen mit vorheriger Version. Keine Löschungen.", "Source → destination. Updates keep a previous version. No deletions.", "Источник → назначение. Обновления с сохранением прежней версии. Без удаления файлов."],
        ["Heading"] = ["Deine Sicherung", "Your backup", "Резервная копия"],
        ["Subtitle"] = ["Ordner auswählen. Vorschau prüfen. Sicher kopieren.", "Choose folders. Review the preview. Copy with confidence.", "Выберите папки, проверьте план и запустите копирование."],
        ["Name"] = ["Name", "Name", "Название"],
        ["Source"] = ["Quelle", "Source", "Источник"],
        ["Destination"] = ["Ziel", "Destination", "Назначение"],
        ["Browse"] = ["Auswählen", "Browse", "Выбрать"],
        ["Preview"] = ["Dateivorschau", "File preview", "Предпросмотр файлов"],
        ["Inspect"] = ["Prüfen", "Preview", "Проверить"],
        ["Copy"] = ["Synchronisieren", "Synchronize", "Синхронизировать"],
        ["Save"] = ["Speichern", "Save task", "Сохранить"],
        ["Delete"] = ["Entfernen", "Remove task", "Убрать задачу"],
        ["Cancel"] = ["Abbrechen", "Cancel", "Отмена"],
        ["Action"] = ["Aktion", "Action", "Действие"],
        ["Path"] = ["Relativer Dateipfad", "Relative file path", "Путь внутри папки"],
        ["CopyNewFile"] = ["Neue Datei", "New file", "Новый файл"],
        ["Unchanged"] = ["Identisch", "Identical", "Совпадает"],
        ["Conflict"] = ["Konflikt · übersprungen", "Conflict · skipped", "Конфликт · пропуск"],
        ["UpdateDestinationFile"] = ["Aktualisieren", "Update", "Обновить"],
        ["Empty"] = ["Wähle Quelle und Ziel und prüfe den Plan. Dabei werden keine Dateien geändert.", "Choose source and destination, then review a preview. Preview does not change files.", "Выберите источник и назначение, затем проверьте план. Проверка не меняет файлы."],
        ["Ready"] = ["Bereit", "Ready", "Готово"],
        ["NewName"] = ["Neue Sicherung", "New backup", "Новая копия"],
        ["Running"] = ["Ordner werden geprüft …", "Inspecting folders …", "Проверяем папки…"],
        ["Cancelled"] = ["Abgebrochen. Bereits kopierte Dateien bleiben erhalten.", "Cancelled. Files already copied are retained.", "Отменено. Уже скопированные файлы сохранены."],
        ["Summary"] = ["{0} neue Dateien  ·  {1} identisch  ·  {2} übersprungen", "{0} new files  ·  {1} identical  ·  {2} skipped", "Новых: {0}  ·  Совпадает: {1}  ·  Пропущено: {2}"],
        ["Saved"] = ["Aufgabe gespeichert.", "Task saved.", "Задача сохранена."],
        ["Removed"] = ["Aufgabe entfernt. Deine Dateien bleiben erhalten.", "Task removed. Your files are preserved.", "Задача убрана. Ваши файлы сохранены."],
        ["Select"] = ["Wähle zuerst eine gespeicherte Aufgabe aus.", "Select a saved task first.", "Сначала выберите сохранённую задачу."],
        ["Confirm"] = ["{0} neue Dateien nach «{1}» kopieren? Bestehende Dateien werden nicht überschrieben.", "Copy {0} new files to “{1}”? Existing files will not be overwritten.", "Скопировать {0} новых файлов в «{1}»? Существующие файлы не будут перезаписаны."],
        ["ConfirmTitle"] = ["Synchronisierung bestätigen", "Confirm synchronization", "Подтвердите синхронизацию"],
        ["RemoveConfirm"] = ["Aufgabe «{0}» entfernen? Dateien bleiben erhalten.", "Remove task “{0}”? Files will be preserved.", "Убрать задачу «{0}»? Файлы сохранятся."],
        ["Done"] = ["{0} Dateien kopiert. {1} Konflikte übersprungen.", "Copied {0} files. Skipped {1} conflicts.", "Скопировано файлов: {0}. Пропущено конфликтов: {1}."],
        ["Copying"] = ["Dateien werden synchronisiert …", "Synchronizing files …", "Синхронизируем файлы…"],
        ["StoreBlocked"] = ["Die Aufgabenliste konnte nicht gelesen werden. Änderungen sind gesperrt, damit sie nicht überschrieben wird.", "The task list could not be read. Saving is disabled to protect the existing list.", "Не удалось прочитать список задач. Сохранение заблокировано, чтобы не затереть список."],
        ["Changed"] = ["Die Auswahl wurde geändert. Bitte erneut prüfen.", "The selection changed. Please preview again.", "Выбор изменился. Проверьте план заново."],
        ["SaveFirst"] = ["Speichere die Aufgabe, dann prüfe sie vor dem Kopieren.", "Save the task, then preview before copying.", "Сохраните задачу и проверьте план перед копированием."],
        ["Error"] = ["Vorgang fehlgeschlagen. Prüfe die Ordner und versuche es erneut.", "Operation failed. Check the folders and try again.", "Операция не выполнена. Проверьте папки и повторите попытку."],
        ["Missing"] = ["Ein Ordner oder eine Datei ist nicht mehr verfügbar. Bitte erneut prüfen.", "A folder or file is no longer available. Please preview again.", "Папка или файл больше недоступны. Проверьте план заново."],
        ["Denied"] = ["Zugriff verweigert. Wähle einen zugänglichen Ordner.", "Access denied. Choose an accessible folder.", "Нет доступа. Выберите доступную папку."],
        ["Invalid"] = ["Prüfe den Namen und die Pfade: Quelle und Ziel müssen getrennte, vorhandene Ordner sein. Jede Aufgabe braucht ein eigenes Ordnerpaar.", "Check the name and paths: source and destination must be separate existing folders. Each task needs a unique folder pair.", "Проверьте имя и пути: источник и назначение должны быть отдельными существующими папками. Пара папок не должна повторять другую задачу."],
        ["IoError"] = ["Dateizugriff fehlgeschlagen: Datei geändert, gesperrt, verknüpft oder Datenträger nicht verfügbar. Bitte erneut prüfen.", "File access failed: a file changed, is locked, is a link, or storage is unavailable. Please preview again.", "Ошибка доступа: файл изменён, занят, является ссылкой или диск недоступен. Проверьте план заново."],
        ["Partial"] = ["Vorgang unterbrochen. {0} Dateien wurden kopiert; sie bleiben erhalten. {1}", "Operation interrupted. {0} files were copied and retained. {1}", "Операция прервана. Скопировано и сохранено файлов: {0}. {1}"],
        ["ReportWarning"] = ["Kopie fertig, aber Bericht oder Aufgabenstatus konnte nicht gespeichert werden. Prüfe das Ziel vor einem weiteren Lauf.", "Copy complete, but the report or task state could not be saved. Check the destination before another run.", "Копирование завершено, но отчёт или состояние задачи не удалось сохранить. Проверьте папку назначения перед следующим запуском."],
        ["LanguageWarning"] = ["Sprache geändert, konnte aber nicht gespeichert werden.", "Language changed but the preference could not be saved.", "Язык изменён, но сохранить выбор не удалось."],
    };
    public static string Get(string key, params object[] args)
    {
        var value = Entries[key][Language == "ru" ? 2 : Language == "en" ? 1 : 0];
        return args.Length == 0 ? value : string.Format(CultureInfo.GetCultureInfo(Language), value, args);
    }

    // Nested status messages must resolve their language when displayed, too.
    public sealed record Reference(string Key)
    {
        public override string ToString() => Get(Key);
    }
}
